// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtleakeiowgwlunabkrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0bGVha2Vpb3dnd2x1bmFia3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjU4NTcsImV4cCI6MjA3MjA0MTg1N30.G6fSAWkVvXUVDCgfB_oCJFhwzFk5SL5RkVnBWMV8PBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});